server:
  host: 192.168.10.98
  port: 9999
  netty:
    bossCount: 1
    workerCount: 10
    keep-alive: true
    backlog: 512

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leakmaster_db
    username: root
    password: scsol92595
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

    properties:
      hibernate:
        ddl-auto: none
        generate-ddl: false
        show-sql: true
        format_sql: true
        use_sql_comments: true

  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace






sensor:
  file-path: /home/scsol/public_html/leak_data_gong/